In [61]:
import os
os.listdir("/content/")

['.config',
 'tmdb_5000_credits.csv.zip',
 'sample_data',
 'tmdb_5000_credits.csv']

In [62]:
import zipfile
with zipfile.ZipFile("/content/tmdb_5000_credits.csv.zip","r") as zip_ref: zip_ref.extractall("/content/")

In [63]:
os.listdir("/content/")

['.config',
 'tmdb_5000_credits.csv.zip',
 'sample_data',
 'tmdb_5000_credits.csv']

In [64]:
import pandas as pd

movies = pd.read_csv("/content/tmdb_5000_credits.csv")

In [65]:
movies.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [66]:
movies = movies[['title', 'cast']]
movies.head()

,title,cast
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""..."
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa..."
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr..."
3,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba..."
4,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c..."

In [67]:
import ast
def clean_cast(text):
   name = []
   for i in ast.literal_eval(text):
    names.append(i['name'])
    return " ".join(names)

    movies['cast_clean'] = movies['cast'].apply(clean_cast)
    movies.head()

In [68]:
import ast
def clean_cast(text):
  names = []
  for i in ast.literal_eval(text):
    names.append(i['name'])
  return " ".join(names)
movies['cast_clean']= movies['cast'].apply(clean_cast)
movies.head()

,title,cast,cast_clean
0,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",Sam Worthington Zoe Saldana Sigourney Weaver S...
1,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",Johnny Depp Orlando Bloom Keira Knightley Stel...
2,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",Daniel Craig Christoph Waltz Léa Seydoux Ralph...
3,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",Christian Bale Michael Caine Gary Oldman Anne ...
4,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",Taylor Kitsch Lynn Collins Samantha Morton Wil...

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
matrix = tfidf.fit_transform(movies['cast_clean'])

In [70]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(matrix)

In [71]:
def recommend(movie_name):
    movie_name = movie_name.lower()
    movies['title_lower'] = movies['title'].str.lower()

    if movie_name not in movies['title_lower'].values:
        print("Movie not found ❌")
        return

    index = movies[movies['title_lower'] == movie_name].index[0]
    scores = list(enumerate(similarity[index]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    print("Recommended Movies:")
    for i in scores:
        print(movies.iloc[i[0]].title)

In [72]:
#1
recommend("Avatar")

Recommended Movies:
The Royal Tenenbaums
The Dark Knight
Charlie's Angels
Idiocracy
Bottle Rocket

In [73]:
#2
movie_name = input("Enter movie name: ")
recommend(movie_name)

Enter movie name: gerry
Recommended Movies:
Chasing Amy
200 Cigarettes
The Killer Inside Me
Ocean's Eleven
To Die For

In [74]:
#3
def recommend_movie():
    movie_name = input("Enter movie name: ")
    recommend(movie_name)

recommend_movie()

Enter movie name: hulk
Recommended Movies:
All the Pretty Horses
The Finest Hours
Battle of the Year
The Invasion
Far from Heaven

In [77]:
#4
while True:
    movie_name = input("Enter movie name (or type exit): ")

    if movie_name.lower() == "exit":
        print("Thank you for using Movie Recommendation System 🎬")
        break

    recommend(movie_name)
    print("-" * 40)

Enter movie name (or type exit): interstellar
Recommended Movies:
Gerry
The Dark Knight Rises
A Most Violent Year
88 Minutes
Jay and Silent Bob Strike Back
----------------------------------------
Enter movie name (or type exit): gerry
Recommended Movies:
Chasing Amy
200 Cigarettes
The Killer Inside Me
Ocean's Eleven
To Die For
----------------------------------------
Enter movie name (or type exit): harry
Movie not found ❌
----------------------------------------
Enter movie name (or type exit): die
Movie not found ❌
----------------------------------------
Enter movie name (or type exit): to die for
Recommended Movies:
Gerry
Chasing Amy
200 Cigarettes
Clay Pigeons
Birth
----------------------------------------
Enter movie name (or type exit): exit
Thank you for using Movie Recommendation System 🎬

In [78]:
#5
def recommend(movie_name):
    movie_name = movie_name.lower()
    movies['title_lower'] = movies['title'].str.lower()

    matches = movies[movies['title_lower'].str.contains(movie_name)]

    if matches.empty:
        print("Movie not found ❌")
        return

    index = matches.index[0]
    scores = list(enumerate(similarity[index]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    print("Recommended Movies:")
    for i in scores:
        print(movies.iloc[i[0]].title)

In [79]:
movie_name = input("Enter movie name: ")
recommend(movie_name)

Enter movie name: harry
Recommended Movies:
Harry Potter and the Order of the Phoenix
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Goblet of Fire
Harry Potter and the Chamber of Secrets
Harry Potter and the Philosopher's Stone

In [80]:
while True:
    movie_name = input("Enter movie name (or type exit): ")

    if movie_name.lower() == "exit":
        print("Thank you for using Movie Recommendation System 🎬")
        break

    recommend(movie_name)
    print("-" * 40)

Enter movie name (or type exit): harry
Recommended Movies:
Harry Potter and the Order of the Phoenix
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Goblet of Fire
Harry Potter and the Chamber of Secrets
Harry Potter and the Philosopher's Stone
----------------------------------------
Enter movie name (or type exit): die
Recommended Movies:
Captain America: Civil War
Avengers: Age of Ultron
The Avengers
All Is Lost
Thor
----------------------------------------
Enter movie name (or type exit): hulk
Recommended Movies:
All the Pretty Horses
The Finest Hours
Battle of the Year
The Invasion
Far from Heaven
----------------------------------------
Enter movie name (or type exit): exit
Thank you for using Movie Recommendation System 🎬